'\" t
.\"     Title: html2info
.\"    Author: [see the "AUTHORS" section]
.\" Generator: Asciidoctor 1.5.4
.\"      Date: 2016-02-17
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "HTML2INFO" "1" "2016-02-17" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
html2info \- converts troff2page\- and tex2page\-generated HTML documents to GNU Info docs.
.SH "SYNOPSIS"
.sp
.if n \{\
.RS 4
.\}
.nf
html2info <pathname>
.fi
.if n \{\
.RE
.\}
.SH "DESCRIPTION"
.sp
html2info converts HTML documents created by troff2page(1) or
tex2page(1) into GNU Info documents. While it can be called by
itself, it is also automatically called by troff2page(1) provided
the document has called the macro
.sp
.if n \{\
.RS 4
.\}
.nf
\&.troff2info
.fi
.if n \{\
.RE
.\}
.sp
A good place to place the .troff2info call is in the
\f[CR].troff2pagerc.tmac\fP macro file, which troff2page(1) always takes
care to load if it can find it.
.SH "AVAILABILITY"
.sp
html2info is part of the troff2page(1) distribution.
.SH "SEE ALSO"
.sp
groff(1), troff2page(1)