= troff2page(1)

== NAME

troff2page - makes Web pages from troff documents

== SYNOPSIS

    troff2page <pathname>
    troff2page --help
    troff2page --version

== DESCRIPTION

troff2page converts troff (_-man_ and _-ms_) documents into HTML web
pages and Info documents. E.g.,

    troff2page jobname.ms

creates an output HTML document that consists of _jobname.html_
and possibly other files _jobname-Z-H-1.html_,
_jobname-Z-H-2.html_, etc., which are linked by navigation to
_jobname.html_.

    troff2page --version

displays the troff2page version.

    troff2page --help

displays the version and a pointer to the comprehensive online
manual, http://ds26gte.github.io/troff2page/index.html, whose troff
source is included in the troff2page distribution.

troff2page called with no argument exits with a “called with no
argument” message.

== OPTIONS

troff2page does not support options as groff can. Indeed,
_--help_ and _--version_ are not really options: if they happen
to name actual files, troff2page will happily attempt to process
them as input documents.

However, additional information may be fed to troff2page via the
specially named macro file _.troff2pagerc.tmac_. Thus, a _-mpca_
groff option would translate to the line

    .mso pca.tmac

in _.troff2pagerc.tmac_.

troff2page loads _.troff2pagerc.tmac_, if it can find it in the
macro directories, before processing its argument file.

Note that groff itself does not load _.troff2pagerc.tmac_
automatically.  But that is presumably OK, since you are using
groff command-line options to specify the same information
anyway.  If you do want groff to pick up this file, you can use
the option _-m.troff2pagerc_.

If the input file is recognizably a man page (i.e., it has the
command _.TH_), both troff2page and groff will load, if it
exists, the init file _man.local_ in the home directory.

== COMMANDS

troff2page recognizes most of the commands (requests, macros,
diversions, strings, escapes, glyphs) of raw troff and its _-ms_
and _-man_ macro packages. The syntax recognized is the improved
kind supported by groff (http://gnu.org/software/groff) and Heirloom
troff (http://github.com/n-t-roff/heirloom-doctools), i.e., macro,
string, and glyph names can be arbitrarily long, and strings can
have arguments.  Most of the commands are converted to their
obvious HTML equivalent.  E.g., _-ms_’s footnotes have a
straightforward translation in the HTML, with the footnote text
set at the bottom of the HTML page, and with the footnote markers
in the body and the footnote hyperlinking to each other.  Please
consult troff and groff documentation for the commands.

The troff2page distribution also includes the _mpca_ submodule
that contains several useful macro files. Both groff and
troff2page can process these macro files, and give compatible
results. Please see the troff2page manual for further details.

== INFO DOCS

You can call the macro

  .troff2info

within your document to signal to troff2page that it should also
create an Info document.

A good place to place the _.troff2info_ call is in your
_.troff2pagerc.tmac_ file, as it is relevant only to troff2page
and not to groff.

== SYSTEM REQUIREMENTS

_troff2page_ requires Lua. For more information, please see the 
file _INSTALL.adoc_ in the
distribution.

== AVAILABILITY

troff2page is downloadable from http://github.com/ds26gte/troff2page.

== SEE ALSO

groff(1), groff_tmac(5), groff_man(7), groff_ms(7)
